package server

import (
	"ecommerce/internal/config"
	"ecommerce/internal/services"
	// Generated by "make swagger". The blank import is what registers this
	// project's spec with the handler mounted below.
	_ "ecommerce/docs"

	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"
)

type Server struct {
	db             *gorm.DB
	config         *config.Config
	logger         zerolog.Logger
	authService    *services.AuthService
	productService *services.ProductService
	userService    *services.UserService
	uploadService  *services.UploadService
	cartService    *services.CartService
	orderService   *services.OrderService
}

func New(
	db *gorm.DB,
	config *config.Config,
	logger zerolog.Logger,
	authService *services.AuthService,
	productService *services.ProductService,
	userService *services.UserService,
	uploadService *services.UploadService,
	cartService *services.CartService,
	orderService *services.OrderService,
) *Server {
	return &Server{
		db:             db,
		config:         config,
		logger:         logger,
		authService:    authService,
		productService: productService,
		userService:    userService,
		uploadService:  uploadService,
		cartService:    cartService,
		orderService:   orderService,
	}
}

func (s *Server) SetupRoutes() *gin.Engine {
	router := gin.New()

	router.Use(gin.Logger())
	router.Use(gin.Recovery())
	router.Use(s.corsMiddleware())

	router.GET("/health", healthCheck)

	// Swagger UI on /docs/index.html, RapiDoc on /api-docs.
	router.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.StaticFile("/api-docs", "./docs/rapidoc.html")

	router.Static("/uploads", "./uploads")

	api := router.Group("/api/v1")
	{
		auth := api.Group("/auth")
		{
			auth.POST("/register", s.register)
			auth.POST("/login", s.login)
			auth.POST("/refresh", s.refreshToken)
			auth.POST("/logout", s.logout)
		}

		api.GET("/categories", s.getCategories)
		api.GET("/products", s.getProducts)
		api.GET("/products/:id", s.getProduct)

		protectedRoutes := api.Group("/")
		protectedRoutes.Use(s.authMiddleware())
		{
			users := protectedRoutes.Group("/users")
			{
				users.GET("/profile", s.getProfile)
				users.PUT("/profile", s.updateProfile)
				users.GET("/:id", s.getUser)
			}

			products := protectedRoutes.Group("/products")
			{
				products.POST("/", s.adminMiddleware(), s.createProduct)
				products.PUT("/:id", s.adminMiddleware(), s.updateProduct)
				products.DELETE("/:id", s.adminMiddleware(), s.deleteProduct)
				products.POST("/:id/images", s.adminMiddleware(), s.uploadProductImage)
				products.DELETE("/:id/images/:imageId", s.adminMiddleware(), s.deleteProductImage)
			}

			cart := protectedRoutes.Group("/cart")
			{
				cart.GET("/", s.getCart)
				cart.DELETE("/", s.clearCart)
				cart.POST("/items", s.addToCart)
				cart.PUT("/items/:itemId", s.updateCartItem)
				cart.DELETE("/items/:itemId", s.removeFromCart)
			}

			orders := protectedRoutes.Group("/orders")
			{
				orders.POST("/", s.createOrder)
				orders.GET("/", s.getOrders)
				orders.GET("/:id", s.getOrder)
			}

			categories := protectedRoutes.Group("/categories")
			{
				categories.POST("/", s.adminMiddleware(), s.createCategory)
				categories.PUT("/:id", s.adminMiddleware(), s.updateCategory)
				categories.DELETE("/:id", s.adminMiddleware(), s.deleteCategory)
			}
		}
	}

	return router
}
